services:
  app:
    build: .
    container_name: nelon_shift_app
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/nelon_shift_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    networks:
      - nelon_net

  postgres:
    image: postgres:17
    container_name: nelon_shift_db
    restart: always
    environment:
      POSTGRES_DB: nelon_shift_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nelon_net

  redis:
    image: redis:7
    container_name: nelon_shift_redis
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nelon_net

volumes:
  postgres_data:
  redis_data:

networks:
  nelon_net: